#!/usr/bin/bash -e

if [ -z "$1" ]; then
  echo "No package supplied"
  echo "make new PKG=<pkgname>"
fi

pkg=${1}

# git subrepo init $pkg --remote ssh://aur@aur.archlinux.org/${pkg}.git --branch master
mkdir $pkg
cp .templates/PKGBUILD $pkg
sed -i "s/TEMPLATE/$pkg/" $pkg/PKGBUILD
cp .templates/.gitignore $pkg
cp .templates/Makefile $pkg
sed -i "s/TEMPLATE/$pkg/" $pkg/Makefile
