#!/usr/bin/bash -e

if [ -z "$1" ]; then
  echo "No package supplied"
  echo "make publish PKG=<pkgname>"
fi

pkg=${1}

cd $pkg

make clean
make build
#make install
make update-srcinfo

git add .
pkg_pkgver=$(pacman -Q $pkg)
# a dash of gitmoji
git commit --allow-empty -m":bookmark: $pkg_pkgver"
git commit --amend --allow-empty

cd ..
# typically `main`, but...
# https://stackoverflow.com/a/9753364
upstream=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)"|cut -d'/' -f1)
# only push after actually publishing, i.e., successful subrepo push
git subrepo clean "$pkg"
git subrepo push "$pkg" --remote=ssh://aur@aur.archlinux.org/$pkg.git --branch=master --update
git push $upstream main
tagname=$(echo $pkg_pkgver|tr ' ' '/')
# ditto for setting/pushing tag
git tag -a -m"$pkg_pkgver" "$tagname"
git push $upstream $tagname
