#!/usr/bin/bash -e

if [ -z "$1" ]; then
  echo "No package supplied"
  echo "make publish PKG=<pkgname>"
fi

pkg=${1}

cd $pkg

make build
make install
make update-srcinfo

git add .
pkg_pkgver=$(pacman -Q $pkg)
git commit -m"$pkg_pkgver"

cd ..
git subrepo push "$pkg" --remote=ssh://aur@aur.archlinux.org/$pkg.git --branch=master --update
